### PR TITLE
[+][UPD][Ressources] - Logo elastic updated

### PR DESCRIPTION
**Pull request by nashvinxtn**
Logo elastic.co updated

### CODE REVIEW

**Comment by nashvinxtn** [comment]
New logo comitted for expat.com

**Comment by Humeira** [comment]
Thanks @nashvinxtn

**Comment by MrSunshyne** [comment]
@Humeira The branch is not correct, this should be merged into `mscraftsman:soft-launch`

**Comment by Humeira** [comment]
@MrSunshyne oh no :/ 
I thought `master` is the current tracking branch

**Pull request merged**
