### PR TITLE
Soft launch

### PR DESCRIPTION
**Pull request by nashvinxtn**
#Add silver sponsor logo - Teamonite

### CODE REVIEW

**Comment by nashvinxtn** [comment]
Also concerning 'Ceridian' logo, i need to rework size but cant get it in softlaunch. @MrSunshyne @jochenkirstaetter. Thanks in advance.

**Comment by nashvinxtn** [comment]
I have re work the size for Ceridian logo and commit on soft-launch. For the conflicts i don't see any it on my branch as i didn't get the logo after a pull.

**Comment by MrSunshyne** [comment]
hi @nashvinxtn , i resolved the conflict locally and merged into soft-launch. Good to go ! 

thanks

**Comment by nashvinxtn** [comment]
@MrSunshyne thnks

**Pull request merged**
