### PR TITLE
F variable font

### PR DESCRIPTION
**Pull request by Saamiyah**
# Description
I used the variable font Gingham as it seemed more appropriate than Decovar for the website. 
Decovar has some openings in the lines which can be hard to read mostly for paragraphs.
http://koe.berlin/variablefont/

Fixes # (issue)
#54

## Type of change
- [x] New feature (non-breaking change which adds functionality)

### CODE REVIEW

**Comment by MrSunshyne** [comment]
The 'outline' effect of the titles is essential to keep the spirit of the design. Can you try decovar instead?

merged meanwhile on f-variable-fonts. Thank you for the PR

**Comment by vchellen** [comment]
Hello,

I'll validate the new fonts with the designers and let you know.

Thanks for the input

**Comment by MrSunshyne** [comment]
@vchellen Feel free to let your designer suggest any other variable font. 

The idea here is to break off from common web practices and adopt one variable font that has the ability to look drastically different(depending on its properties) and of course, still look similar to the design AND look beautiful. 

Goals : 
1. Reduce load time
2. Add cool new web tech to the website

See here for demo of Decovar : https://www.axis-praxis.org
original issue here:  #54

**Comment by vchellen** [comment]
Just pulled the repo and check with my Designer.. A big NO GO for him as it spoils the whole look and feel of the website. May be next year when we have a wider range of supported Variable fonts.

**Comment by vchellen** [comment]
we don't gain enough vs what we lose as general ambiance for the website

**Pull request merged**
