### PR TITLE
typo fix room name

### PR DESCRIPTION
**Pull request by codarrenvelvindron**
# Description

Room name contains a typo:
Accelerator instead of Accelarator
https://www.voilahotel.mu/conference-room-mauritius/meeting-room-floor-plan/accelerator.html

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

untested, just a typo, shouldn't break things

### CODE REVIEW

**Comment by MrSunshyne** [comment]
@vchellen can you confirm which one is being used in sessionize admin ? 
merging this will break the sessions page.

**Comment by vchellen** [comment]
Will confirm this tnite.. sessionize session builder is just horrible to view on mobile phone

**Comment by vchellen** [comment]
Guys, I've just change the name in sessionize to Accelerator , can you check now if it's ok ?

**Comment by MrSunshyne** [comment]
@vchellen this broke the sessions page. can you put it back until @jochenkirstaetter is availble to pull on prod ?

**Comment by codarrenvelvindron** [comment]
@MrSunshyne @vchellen  Changed some other file that contained the class name and forced push, please see if fixed now. 

I initially did not change it thinking it would be compiled somehow and added, but l guess it's not...

**Comment by MrSunshyne** [comment]
@codarrenvelvindron Files in the `dist` folder should not be changed as they are generated at compile time and would be overridden. 

The initial PR is good, but i'm not merging since the typo is found in the backoffice. I intentionally used the wrong 'accelarator' key because that's what the API was sending. 

Ideally the typo and the backoffice should be fixed and deployed simultaneously.

**Comment by vchellen** [comment]
Reverted back for now

**Pull request merged**
